version: '3.8'

networks:
  rk9-tier:
    driver: bridge
    name: rk9-tier

services:
    mongodb:
        image: bitnami/mongodb:4.2
        volumes: 
            - mongodata:/bitnami/mongodb
        networks:
            - rk9-tier
        ports:
            - '27017:27017'
    backend:
        build: 
            context: .
            dockerfile: backend-dev.Dockerfile
        image: 'rk9-webapp-backend:dev'
        command: sh -c "/wait && npm run dev:backend"
        ports:
            - '7777:7777'
            - '9229:9229'
        environment: 
            - DB_URL=mongodb://mongodb:27017/rk9
            - API_PORT=7777
            - WAIT_HOSTS=mongodb:27017
        networks:
            - rk9-tier
        volumes:
            - .:/srv/app:rw
            - /srv/app/node_modules/
            - /srv/app/packages/backend/node_modules/
        depends_on: 
            - mongodb

volumes:
    mongodata: {}
